server:
  port: 8082

spring:
  application:
    name: usuario-service

  datasource:
    url: jdbc:mysql://host.docker.internal:3306/gym_db
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: "mi_clave_super_segura_de_gym_2026_minimo_32_chars"